# Generated by Django 5.2.9 on 2026-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
